/********************************************************************************
** Form generated from reading UI file 'aboutdialog.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ABOUTDIALOG_H
#define UI_ABOUTDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QTextBrowser>

QT_BEGIN_NAMESPACE

class Ui_AboutDialog
{
public:
    QDialogButtonBox *buttonBox;
    QTextBrowser *textBrowser;

    void setupUi(QDialog *AboutDialog)
    {
        if (AboutDialog->objectName().isEmpty())
            AboutDialog->setObjectName(QStringLiteral("AboutDialog"));
        AboutDialog->resize(400, 300);
        buttonBox = new QDialogButtonBox(AboutDialog);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(30, 240, 341, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        textBrowser = new QTextBrowser(AboutDialog);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(30, 20, 331, 201));

        retranslateUi(AboutDialog);
        QObject::connect(buttonBox, SIGNAL(accepted()), AboutDialog, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), AboutDialog, SLOT(reject()));

        QMetaObject::connectSlotsByName(AboutDialog);
    } // setupUi

    void retranslateUi(QDialog *AboutDialog)
    {
        AboutDialog->setWindowTitle(QApplication::translate("AboutDialog", "3GPP Decoder v1.0", 0));
        textBrowser->setHtml(QApplication::translate("AboutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">3GPP Decoder Linux v1.0</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">Author: </span><a href=\"prashant@3glteinfo.com\"><span style=\" fon"
                        "t-family:'MS Shell Dlg 2'; font-size:8pt; text-decoration: underline; color:#0000ff;\">Prashant Panigrahi</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">Website: </span><a href=\"http://www.3glteinfo.com/\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; text-decoration: underline; color:#0000ff;\">www.3glteinfo.com</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\">Copyright</span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#c0c0c0;\"> </spa"
                        "n><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\">(C)</span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\">2017</span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#c0c0c0;\">  </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\">Prashant</span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\">Panigrahi</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2'; font-size:8pt; color:#008000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Courier New,courier'; font-s"
                        "ize:8pt; color:#008000;\">This</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">program</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">is</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">free</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">software:</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">you</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; col"
                        "or:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">can</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">redistribute</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">it</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">and/or</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">modify it</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#0080"
                        "00;\">under</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">terms</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">of</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">GNU</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span "
                        "style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">General</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">Public</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">License</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">as</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">published</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">by</span><span style=\""
                        " font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">Free</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">Software</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">Foundation,</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">either</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-fa"
                        "mily:'Courier New,courier'; font-size:8pt; color:#008000;\">version</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">3</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">of</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">License,</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">or (at</span><span style=\" font-family:'Courier "
                        "New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">your</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">option)</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">any</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">later</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">version.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span sty"
                        "le=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">This</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">program</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">is</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">distributed</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#00"
                        "8000;\">in</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">hope</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">that</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">it</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">will</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span "
                        "style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">be</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">useful, but</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">WITHOUT</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">ANY</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">WARRANTY;</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">without</span><span st"
                        "yle=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">even</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">implied</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">warranty</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">of MERCHANTABILITY</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span st"
                        "yle=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">or</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">FITNESS</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">FOR</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">A</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">PARTICULAR</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">PURPOSE.</span><span style=\" fon"
                        "t-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\">  </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">See</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the GNU</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">General</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">Public</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">License</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:"
                        "'Courier New,courier'; font-size:8pt; color:#008000;\">for</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">more</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">details.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">You</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-siz"
                        "e:8pt; color:#008000;\">should</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">have</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">received</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">a</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">copy</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">of</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0"
                        "c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">the</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">GNU</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">General</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">Public</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">License along</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">"
                        "with</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">this</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">program.</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\">  </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">If</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">not,</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">see</span><span style=\" font-family:'Courier New,courier'; font-size:8pt; color:#c0c0c0;\"> </span><span s"
                        "tyle=\" font-family:'Courier New,courier'; font-size:8pt; color:#008000;\">&lt;http://www.gnu.org/licenses/&gt;</span></p></body></html>", 0));
    } // retranslateUi

};

namespace Ui {
    class AboutDialog: public Ui_AboutDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ABOUTDIALOG_H
